CREATE TABLE [dbo].[Book]
(
	[Id] INT NOT NULL IDENTITY (1,1),
    [Title] VARCHAR(50) NOT NULL,
	[CreatedAt] DATETIME2 NOT NULL DEFAULT (SYSUTCDATETIME()),
	[UpdatedAt] DATETIME2 NOT NULL DEFAULT (SYSUTCDATETIME()),
	CONSTRAINT [PK_Book] PRIMARY KEY CLUSTERED (Id ASC),
)
