CREATE TABLE [dbo].[User]
(
	[Id] INT NOT NULL IDENTITY (1,1) PRIMARY KEY,
    [Name] NCHAR(20) NOT NULL, 
    [Email] VARCHAR(50) NOT NULL, 
    [Password] VARCHAR(50) NOT NULL,
    [CreatedAt] DATETIME2 NOT NULL DEFAULT (SYSUTCDATETIME()),
	[UpdatedAt] DATETIME2 NOT NULL DEFAULT (SYSUTCDATETIME())
    CONSTRAINT [CK_Email_Unique] UNIQUE NONCLUSTERED ([Email] ASC),

)
