CREATE TABLE [dbo].[UserBook]
(
	[Id] INT NOT NULL IDENTITY (1,1) PRIMARY KEY,
	[UserId] INT NOT NULL,
	[BookId] INT NOT NULL,
	[CreatedAt] DATETIME2 NOT NULL DEFAULT (SYSUTCDATETIME()),
	[UpdatedAt] DATETIME2 NOT NULL DEFAULT (SYSUTCDATETIME())
	CONSTRAINT [FK_UserBook_User] FOREIGN KEY([UserId]) REFERENCES [dbo].[User] ([Id]),
    CONSTRAINT [FK_UserBook_Book] FOREIGN KEY([BookId])REFERENCES [dbo].[Book] ([Id])
)
