// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System.Collections.Generic;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	[Table("AspNetRoles")]
	public class AspNetRole
	{
		[Column("Id"              , CanBeNull = false, IsPrimaryKey = true)] public string  Id               { get; set; } = null!; // nvarchar(450)
		[Column("Name"                                                    )] public string? Name             { get; set; } // nvarchar(256)
		[Column("NormalizedName"                                          )] public string? NormalizedName   { get; set; } // nvarchar(256)
		[Column("ConcurrencyStamp"                                        )] public string? ConcurrencyStamp { get; set; } // nvarchar(max)

		#region Associations
		/// <summary>
		/// FK_AspNetRoleClaims_AspNetRoles_RoleId backreference
		/// </summary>
		[Association(ThisKey = nameof(Id), OtherKey = nameof(AspNetRoleClaim.RoleId))]
		public IEnumerable<AspNetRoleClaim> AspNetRoleClaims { get; set; } = null!;

		/// <summary>
		/// FK_AspNetUserRoles_AspNetRoles_RoleId backreference
		/// </summary>
		[Association(ThisKey = nameof(Id), OtherKey = nameof(AspNetUserRole.RoleId))]
		public IEnumerable<AspNetUserRole> AspNetUserRoles { get; set; } = null!;
		#endregion
	}
}
