// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	[Table("AspNetUserLogins")]
	public class AspNetUserLogin
	{
		[Column("LoginProvider"      , CanBeNull = false, IsPrimaryKey = true, PrimaryKeyOrder = 0)] public string  LoginProvider       { get; set; } = null!; // nvarchar(450)
		[Column("ProviderKey"        , CanBeNull = false, IsPrimaryKey = true, PrimaryKeyOrder = 1)] public string  ProviderKey         { get; set; } = null!; // nvarchar(450)
		[Column("ProviderDisplayName"                                                             )] public string? ProviderDisplayName { get; set; } // nvarchar(max)
		[Column("UserId"             , CanBeNull = false                                          )] public string  UserId              { get; set; } = null!; // nvarchar(450)

		#region Associations
		/// <summary>
		/// FK_AspNetUserLogins_AspNetUsers_UserId
		/// </summary>
		[Association(CanBeNull = false, ThisKey = nameof(UserId), OtherKey = nameof(AspNetUser.Id))]
		public AspNetUser User { get; set; } = null!;
		#endregion
	}
}
