// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	[Table("AspNetUserClaims")]
	public class AspNetUserClaim
	{
		[Column("Id"        , IsPrimaryKey = true , IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)] public int     Id         { get; set; } // int
		[Column("UserId"    , CanBeNull    = false                                                             )] public string  UserId     { get; set; } = null!; // nvarchar(450)
		[Column("ClaimType"                                                                                    )] public string? ClaimType  { get; set; } // nvarchar(max)
		[Column("ClaimValue"                                                                                   )] public string? ClaimValue { get; set; } // nvarchar(max)

		#region Associations
		/// <summary>
		/// FK_AspNetUserClaims_AspNetUsers_UserId
		/// </summary>
		[Association(CanBeNull = false, ThisKey = nameof(UserId), OtherKey = nameof(AspNetUser.Id))]
		public AspNetUser User { get; set; } = null!;
		#endregion
	}
}
