// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	[Table("AspNetUserTokens")]
	public class AspNetUserToken
	{
		[Column("UserId"       , CanBeNull = false, IsPrimaryKey = true, PrimaryKeyOrder = 0)] public string  UserId        { get; set; } = null!; // nvarchar(450)
		[Column("LoginProvider", CanBeNull = false, IsPrimaryKey = true, PrimaryKeyOrder = 1)] public string  LoginProvider { get; set; } = null!; // nvarchar(450)
		[Column("Name"         , CanBeNull = false, IsPrimaryKey = true, PrimaryKeyOrder = 2)] public string  Name          { get; set; } = null!; // nvarchar(450)
		[Column("Value"                                                                     )] public string? Value         { get; set; } // nvarchar(max)

		#region Associations
		/// <summary>
		/// FK_AspNetUserTokens_AspNetUsers_UserId
		/// </summary>
		[Association(CanBeNull = false, ThisKey = nameof(UserId), OtherKey = nameof(AspNetUser.Id))]
		public AspNetUser AspNetUsersUserId { get; set; } = null!;
		#endregion
	}
}
