// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB;
using LinqToDB.Data;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	public partial class CollegeBooksDb : DataConnection
	{
		public CollegeBooksDb()
		{
			InitDataContext();
		}

		public CollegeBooksDb(string configuration)
			: base(configuration)
		{
			InitDataContext();
		}

		public CollegeBooksDb(DataOptions<CollegeBooksDb> options)
			: base(options.Options)
		{
			InitDataContext();
		}

		partial void InitDataContext();

		public ITable<Book>     Books     => this.GetTable<Book>();
		public ITable<User>     Users     => this.GetTable<User>();
		public ITable<UserBook> UserBooks => this.GetTable<UserBook>();
	}

	public static partial class ExtensionMethods
	{
		#region Table Extensions
		public static Book? Find(this ITable<Book> table, int id)
		{
			return table.FirstOrDefault(e => e.Id == id);
		}

		public static Task<Book?> FindAsync(this ITable<Book> table, int id, CancellationToken cancellationToken = default)
		{
			return table.FirstOrDefaultAsync(e => e.Id == id, cancellationToken);
		}

		public static User? Find(this ITable<User> table, int id)
		{
			return table.FirstOrDefault(e => e.Id == id);
		}

		public static Task<User?> FindAsync(this ITable<User> table, int id, CancellationToken cancellationToken = default)
		{
			return table.FirstOrDefaultAsync(e => e.Id == id, cancellationToken);
		}

		public static UserBook? Find(this ITable<UserBook> table, int id)
		{
			return table.FirstOrDefault(e => e.Id == id);
		}

		public static Task<UserBook?> FindAsync(this ITable<UserBook> table, int id, CancellationToken cancellationToken = default)
		{
			return table.FirstOrDefaultAsync(e => e.Id == id, cancellationToken);
		}
		#endregion
	}
}
