// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	[Table("UserBook")]
	public class UserBook
	{
		[Column("Id"       , IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)] public int      Id        { get; set; } // int
		[Column("UserId"                                                                                     )] public int      UserId    { get; set; } // int
		[Column("BookId"                                                                                     )] public int      BookId    { get; set; } // int
		[Column("CreatedAt"                                                                                  )] public DateTime CreatedAt { get; set; } // datetime2(7)
		[Column("UpdatedAt"                                                                                  )] public DateTime UpdatedAt { get; set; } // datetime2(7)

		#region Associations
		/// <summary>
		/// FK_UserBook_Book
		/// </summary>
		[Association(CanBeNull = false, ThisKey = nameof(BookId), OtherKey = nameof(DataModel.Book.Id))]
		public Book Book { get; set; } = null!;

		/// <summary>
		/// FK_UserBook_User
		/// </summary>
		[Association(CanBeNull = false, ThisKey = nameof(UserId), OtherKey = nameof(DataModel.User.Id))]
		public User User { get; set; } = null!;
		#endregion
	}
}
