-- MERGE generated by running the 'sp_generate_merge' 
-- For more info: https://github.com/readyroll/generate-sql-merge

--   EXEC sp_generate_merge
--   @schema = 'dbo',
--   @table_name ='Book'


USE [CollegeBooks]
GO

--MERGE generated by 'sp_generate_merge' stored procedure
--Originally by Vyas (http://vyaskn.tripod.com/code): sp_generate_inserts (build 22)
--Adapted for SQL Server 2008+ by Daniel Nolan (https://twitter.com/dnlnln)

SET NOCOUNT ON

SET IDENTITY_INSERT [dbo].[Book] ON

MERGE INTO [dbo].[Book] AS [Target]
USING (VALUES
  (1,N'Mi dia de suerte','2024-06-18T18:44:06.0652688','2024-06-18T18:44:06.0652688')
 ,(2,N'Cumpleaños feroz','2024-06-18T18:44:12.7672158','2024-06-18T18:44:12.7672158')
 ,(3,N'Colon agarra viaje a toda costa','2024-06-18T18:44:43.5685601','2024-06-18T18:44:43.5685601')
) AS [Source] ([Id],[Title],[CreatedAt],[UpdatedAt])
ON ([Target].[Id] = [Source].[Id])
WHEN MATCHED AND (
	NULLIF([Source].[Title], [Target].[Title]) IS NOT NULL OR NULLIF([Target].[Title], [Source].[Title]) IS NOT NULL OR 
	NULLIF([Source].[CreatedAt], [Target].[CreatedAt]) IS NOT NULL OR NULLIF([Target].[CreatedAt], [Source].[CreatedAt]) IS NOT NULL OR 
	NULLIF([Source].[UpdatedAt], [Target].[UpdatedAt]) IS NOT NULL OR NULLIF([Target].[UpdatedAt], [Source].[UpdatedAt]) IS NOT NULL) THEN
 UPDATE SET
  [Target].[Title] = [Source].[Title], 
  [Target].[CreatedAt] = [Source].[CreatedAt], 
  [Target].[UpdatedAt] = [Source].[UpdatedAt]
WHEN NOT MATCHED BY TARGET THEN
 INSERT([Id],[Title],[CreatedAt],[UpdatedAt])
 VALUES([Source].[Id],[Source].[Title],[Source].[CreatedAt],[Source].[UpdatedAt])
WHEN NOT MATCHED BY SOURCE THEN 
 DELETE;

DECLARE @mergeError int
 , @mergeCount int
SELECT @mergeError = @@ERROR, @mergeCount = @@ROWCOUNT
IF @mergeError != 0
 BEGIN
 PRINT 'ERROR OCCURRED IN MERGE FOR [dbo].[Book]. Rows affected: ' + CAST(@mergeCount AS VARCHAR(100)); -- SQL should always return zero rows affected
 END
ELSE
 BEGIN
 PRINT '[dbo].[Book] rows affected by MERGE: ' + CAST(@mergeCount AS VARCHAR(100));
 END
GO



SET IDENTITY_INSERT [dbo].[Book] OFF
SET NOCOUNT OFF
GO